name: Terraform Plan
# Runs the workflow on the below events:
# 1. On pull request raised to develop branch
# 2. On pull request raised to main branch
# 3. On push event to develop branch
# 4. On push event to main branch

on:
  workflow_call:
    # Required inputs
    inputs:
      env:
        description: "Env name"
        type: string
        required: true
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  # This job runs Terraform Plan
  plan:
    name: Plan (${{ inputs.env }})
    runs-on: ubuntu-latest
    steps:
      # Checkout project
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Logging in to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region-name }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}

      # Install Terraform CLI
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.2"

      # Intialization of Terraform project
      - name: Terraform init
        run: make ENV=${{ inputs.env}} terraform/init

      # Terraform plan is generated for modules
      - name: Terraform plan
        run: make ENV=${{ inputs.env}} TF_CMD_ARGS='-lock=false -out=terraform_${{ github.sha }}_${{ inputs.env }}.plan' terraform/plan
      
      # Uploading Terrform plan
      - name: Save Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform_${{ github.sha }}_${{ inputs.env }}.plan
          path: infra/terraform/terraform_${{ github.sha }}_${{ inputs.env }}.plan
      
      # - name: Upload Terraform Plan
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: terraform_${{ github.sha }}_${{ inputs.env }}.plan
      #     path: infra/terraform/terraform_${{ github.sha }}_${{ inputs.env }}.plan